---
apiVersion: v1
name: rubyweekly
type: application
version: 0.0.1
appVersion: 0.0.1
description: rubyweekly scrapper
home: https://github.com/zufardhiyaulhaq/rubyweekly
keywords:
  - weekly
  - rubyweekly
